FROM python:3.12-slim

SHELL ["/bin/bash", "-c"]

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /work

RUN apt-get update && apt-get install -y --no-install-recommends gcc curl && curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="~/.local/bin:$PATH"

COPY . /work/

RUN poetry install && poetry build
