[project]
name = "database_crafting"
version = "0.1.0"
description = "Build up the database for the UNet-Model"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[tool.setuptools.packages.find]
exclude = ["data*"]

[tool.distutils.egg_info]
egg_base = "build"
